apiVersion: v1
kind: Template
labels:
metadata:
  annotations:
    description: Application template for ParksMap and NationalParks backend with CI/CD Pipeline
    iconClass: icon-java
  name: nationalpark-pipeline
objects:
- kind: "BuildConfig"
  apiVersion: "v1"
  metadata:
    name: "nationalparks-pipeline"
    annotations:
      pipeline.alpha.openshift.io/uses: '[{"name": "nationalparks-dev", "namespace": "", "kind": "DeploymentConfig"},{"name": "nationalparks-live", "namespace": "", "kind": "DeploymentConfig"}]'
  spec:
    strategy:
      type: "JenkinsPipeline"
      jenkinsPipelineStrategy:
        jenkinsfile: "node {\n  stage 'Build'\n  openshiftBuild(buildConfig: 'nationalparks-dev', showBuildLogs: 'true')\n  \n  stage 'Deploy Dev'\n  openshiftDeploy(deploymentConfig: 'nationalparks-dev')\n\n  stage 'Test Dev'\n  sh 'curl -s http://nationalparks-dev:8080/ws/data/load'\n  sh 'curl -s http://nationalparks-dev:8080/ws/data/all | grep -q \"Grand Canyon National Park\"'\n  \n  stage 'Deploy Live'\n  input 'Promote the Dev image to Live?'\n  openshiftTag(srcStream: 'nationalparks', srcTag: 'latest', destStream: 'nationalparks', destTag: 'live')\n  // openshiftDeploy(deploymentConfig: 'nationalparks-live')\n}"
    triggers:
    - github:
        secret: ${GITHUB_TRIGGER_SECRET}
      type: GitHub
    - generic:
        secret: ${GENERIC_TRIGGER_SECRET}
      type: Generic
parameters:
- description: Github trigger secret
  displayName: GitHub Trigger
  from: '[a-zA-Z0-9]{8}'
  generate: expression
  name: GITHUB_TRIGGER_SECRET
  required: true
- description: Generic build trigger secret
  displayName: Generic Trigger
  from: '[a-zA-Z0-9]{8}'
  generate: expression
  name: GENERIC_TRIGGER_SECRET
  required: true
